[package]
name = "lambda-microegg"
version = "0.1.0"
edition = "2024"

[dependencies]
rustc-hash = "2.1.2"
smallvec = { version = "1.15.1", features = ["union"] }
symbol_table = { version = "0.5.0", features = ["global"] }
indexmap = "2.13.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.128"

[dev-dependencies]
criterion = { version = "0.8.2", default-features = false, features = ["cargo_bench_support"] }

[[bench]]
name = "egraph"
harness = false
